{{- if not .Values.falcondb.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcondb.fullname" . }}-auth
  labels:
    {{- include "falcondb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.falcondb.auth.password }}
  password: {{ .Values.falcondb.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
