apiVersion: v1
kind: Service
metadata:
  name: {{ include "falcondb.fullname" . }}
  labels:
    {{- include "falcondb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: pg
      port: {{ .Values.service.pgPort }}
      targetPort: pg
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "falcondb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "falcondb.fullname" . }}-headless
  labels:
    {{- include "falcondb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: pg
      port: {{ .Values.service.pgPort }}
      targetPort: pg
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
  selector:
    {{- include "falcondb.selectorLabels" . | nindent 4 }}
